import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const languages = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'es', label: 'Español', flag: '🇲🇽' },
  { code: 'pt', label: 'Português', flag: '🇧🇷' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'pl', label: 'Polski', flag: '🇵🇱' },
];

const translations = {
  en: {
    projects: 'Projects',
    activeProjects: 'Active Projects',
    monthlySpend: 'Monthly Spend',
    receiptRate: 'Receipt Rate',
    overBudget: 'Over Budget',
    submitReceipt: 'Submit receipt',
    viewProject: 'View project',
    newProject: 'New project',
    onTrack: 'On Track',
    underBudget: 'Under Budget',
    replayDemo: 'Replay Demo',
    smsReceiptFlow: 'SMS Receipt Flow',
    smsSubtitle: 'Field workers code transactions and submit receipts via text message',
    realTimeCoding: 'Real-Time Transaction Coding',
    waitingSms: 'Waiting for SMS flow to complete...',
    howItWorks: 'How it works',
    howItWorksBody: 'Ramp sends an SMS when a card is swiped. The field worker replies with a project number and cost code keyword. AI matches it to the correct CSI code, captures the receipt photo, and auto-approves if under the set threshold. No app download required.',
    receiptCaptured: 'Receipt Captured',
    aiCostCoded: 'AI Cost-Coded',
    autoApproved: 'Auto-Approved',
    underThreshold: 'Under $500 threshold',
    issueNewCard: 'Issue new card',
    issueCard: 'Issue Card',
    preferredLanguage: 'Preferred Language',
    preferredLanguageHelp: 'SMS notifications and receipt prompts will be sent in this language',
    languageBanner: "Oscar's preferred language: Español — SMS notifications and receipts sent in Spanish",
    tipActiveProjects: 'Projects with at least one transaction in the last 30 days',
    tipMonthlySpend: 'Total card + bill pay spend across all active projects this month',
    tipReceiptRate: 'Percentage of transactions with matched receipts. Target: 100%',
    tipOverBudget: 'Projects where actual spend exceeds pro-rated budget based on completion %',
    missingReceipts: 'receipts missing across 2 projects:',
    request: 'Request',
    projectedOverrun: 'Projected overrun',
    topOverrunCategories: 'Top overrun categories',
    sunsetController: 'Burn rate trending 3% above plan — review Thermal & Moisture spend',
    harborController: '⚠️ 78% budget consumed at 65% completion — flag for weekly review',
    metroController: 'On pace. Next milestone billing due April 1',
    riversideController: 'Under budget by 5% — potential to release contingency early',
    sunsetField: '3 receipts pending — submit by Friday to avoid hold',
    harborField: 'Your card limit resets Monday. $340 remaining this week',
    metroField: 'New safety equipment PO approved — pick up at Ferguson #4412',
    riversideField: 'No action needed — all receipts submitted ✅',
    projectName: 'Project Name',
    projectCode: 'Project Code',
    clientOwner: 'Client / Owner',
    contractType: 'Contract Type',
    contractValue: 'Contract Value',
    startDate: 'Start Date',
    estCompletion: 'Estimated Completion',
    projectAddress: 'Project Address',
    assignedTeam: 'Assigned Team',
    costCodeTemplate: 'Cost Code Template',
    budgetAllocation: 'Budget Allocation',
    approvalThreshold: 'Default Approval Threshold',
    notes: 'Notes',
    cancel: 'Cancel',
    createProject: 'Create Project',
    budget: 'budget',
    spent: 'spent',
    ofBudgetUsed: 'of budget used',
    completion: 'Completion',
    // Project Detail
    transactionDetail: 'Transaction Detail',
    costReport: 'Cost Report',
    transactionsTab: 'Transactions',
    costBreakdownTab: 'Cost Breakdown',
    teamTab: 'Team',
    date: 'Date',
    employee: 'Employee',
    vendor: 'Vendor',
    amount: 'Amount',
    costCode: 'Cost Code',
    aiCoded: 'AI Coded',
    receipt: 'Receipt',
    category: 'Category',
    cardLabel: 'Card',
    project: 'Project',
    aiCoding: 'AI Coding',
    receiptImage: 'Receipt image',
    missing: 'Missing',
    auto: 'Auto',
    override: 'Override',
    uncoded: 'Uncoded',
    // Cost Report
    totalSpent: 'Total Spent',
    remaining: 'Remaining',
    projectedFinal: 'Projected Final',
    variance: 'Variance',
    description: 'Description',
    actual: 'Actual',
    committed: 'Committed',
    forecast: 'Forecast',
    total: 'Total',
    cashPosition: 'Cash Position',
    budgetRemaining: 'Budget Remaining',
    burnRate: 'Burn Rate',
    projectedCompletionDate: 'Projected Completion',
    exportSage: 'Export to Sage 300 CRE',
    exportCsv: 'Export CSV',
    print: 'Print',
    thermalWarning: 'Thermal & Moisture is 2% over budget. Review recent purchases.',
    // Cards
    cards: 'Cards',
    cardHolder: 'Card Holder',
    cardType: 'Card Type',
    projectsCol: 'Project(s)',
    categoryLimitCol: 'Category Limit',
    perTxnLimit: 'Per-Txn Limit',
    dailyLimitCol: 'Daily Limit',
    statusLabel: 'Status',
    employeeLabel: 'Employee',
    assignToProjects: 'Assign to Project(s)',
    categoryRestrictions: 'Category Restrictions',
    perTransactionLimit: 'Per-Transaction Limit',
    dailyLimit: 'Daily Limit',
    approvalRequiredAbove: 'Approval Required Above',
    autoCodeToProject: 'Auto-code to project',
    autoCodeHelp: 'Transactions will be automatically coded to the assigned project',
    physical: 'Physical',
    virtual: 'Virtual',
    holdCmdMultiple: 'Hold Cmd to select multiple',
    // Header
    demoMode: 'Demo Mode — Ramp for Construction',
    switchRole: 'Switch role',
    languageLabel: 'Language',
    // Dashboard drilldowns
    projectsByStatus: 'Projects by status',
    spendBreakdown: 'Spend breakdown this month',
    cardTransactions: 'Card transactions',
    billPayVendors: 'Bill pay (vendors)',
    reimbursements: 'Reimbursements',
    vsLastMonth: 'vs. last month ($298K)',
    addedThisQuarter: '4 projects added this quarter · 0 completed',
    // Command palette
    searchPages: 'Search pages...',
    noResults: 'No results found',
  },
  es: {
    projects: 'Proyectos',
    activeProjects: 'Proyectos Activos',
    monthlySpend: 'Gasto Mensual',
    receiptRate: 'Tasa de Recibos',
    overBudget: 'Sobre Presupuesto',
    submitReceipt: 'Enviar recibo',
    viewProject: 'Ver proyecto',
    newProject: 'Nuevo proyecto',
    onTrack: 'En Curso',
    underBudget: 'Bajo Presupuesto',
    replayDemo: 'Repetir Demo',
    smsReceiptFlow: 'Flujo de Recibos por SMS',
    smsSubtitle: 'Los trabajadores de campo codifican transacciones y envían recibos por mensaje de texto',
    realTimeCoding: 'Codificación de Transacciones en Tiempo Real',
    waitingSms: 'Esperando que se complete el flujo de SMS...',
    howItWorks: 'Cómo funciona',
    howItWorksBody: 'Ramp envía un SMS cuando se usa una tarjeta. El trabajador de campo responde con un número de proyecto y una palabra clave del código de costo. La IA lo asocia al código CSI correcto, captura la foto del recibo y lo aprueba automáticamente si está bajo el umbral establecido. No requiere descarga de aplicación.',
    receiptCaptured: 'Recibo Capturado',
    aiCostCoded: 'Codificado por IA',
    autoApproved: 'Auto-Aprobado',
    underThreshold: 'Bajo umbral de $500',
    issueNewCard: 'Emitir nueva tarjeta',
    issueCard: 'Emitir Tarjeta',
    preferredLanguage: 'Idioma Preferido',
    preferredLanguageHelp: 'Las notificaciones SMS y los recibos se enviarán en este idioma',
    languageBanner: 'Idioma preferido de Oscar: Español — Notificaciones SMS y recibos enviados en español',
    tipActiveProjects: 'Proyectos con al menos una transacción en los últimos 30 días',
    tipMonthlySpend: 'Gasto total de tarjetas y pagos en todos los proyectos activos este mes',
    tipReceiptRate: 'Porcentaje de transacciones con recibos adjuntos. Objetivo: 100%',
    tipOverBudget: 'Proyectos donde el gasto real supera el presupuesto prorrateado según el % de completado',
    missingReceipts: 'recibos faltantes en 2 proyectos:',
    request: 'Solicitar',
    projectedOverrun: 'Sobrecosto proyectado',
    topOverrunCategories: 'Principales categorías con sobrecosto',
    sunsetController: 'Tasa de gasto 3% por encima del plan — revisar gastos de Térmica y Humedad',
    harborController: '⚠️ 78% del presupuesto consumido al 65% de completado — marcar para revisión semanal',
    metroController: 'A buen ritmo. Próxima facturación de hito el 1 de abril',
    riversideController: '5% bajo presupuesto — potencial para liberar contingencia anticipadamente',
    sunsetField: '3 recibos pendientes — enviar antes del viernes para evitar retención',
    harborField: 'Tu límite de tarjeta se reinicia el lunes. $340 restantes esta semana',
    metroField: 'Nueva OC de equipo de seguridad aprobada — recoger en Ferguson #4412',
    riversideField: 'Sin acciones pendientes — todos los recibos enviados ✅',
    projectName: 'Nombre del Proyecto',
    projectCode: 'Código del Proyecto',
    clientOwner: 'Cliente / Propietario',
    contractType: 'Tipo de Contrato',
    contractValue: 'Valor del Contrato',
    startDate: 'Fecha de Inicio',
    estCompletion: 'Fecha Estimada de Finalización',
    projectAddress: 'Dirección del Proyecto',
    assignedTeam: 'Equipo Asignado',
    costCodeTemplate: 'Plantilla de Códigos de Costo',
    budgetAllocation: 'Asignación de Presupuesto',
    approvalThreshold: 'Umbral de Aprobación Predeterminado',
    notes: 'Notas',
    cancel: 'Cancelar',
    createProject: 'Crear Proyecto',
    budget: 'presupuesto',
    spent: 'gastado',
    ofBudgetUsed: 'del presupuesto utilizado',
    completion: 'Completado',
    // Project Detail
    transactionDetail: 'Detalle de Transacción',
    costReport: 'Informe de Costos',
    transactionsTab: 'Transacciones',
    costBreakdownTab: 'Desglose de Costos',
    teamTab: 'Equipo',
    date: 'Fecha',
    employee: 'Empleado',
    vendor: 'Proveedor',
    amount: 'Monto',
    costCode: 'Código de Costo',
    aiCoded: 'Codificado IA',
    receipt: 'Recibo',
    category: 'Categoría',
    cardLabel: 'Tarjeta',
    project: 'Proyecto',
    aiCoding: 'Codificación IA',
    receiptImage: 'Imagen del recibo',
    missing: 'Faltante',
    auto: 'Auto',
    override: 'Corregido',
    uncoded: 'Sin código',
    // Cost Report
    totalSpent: 'Total Gastado',
    remaining: 'Restante',
    projectedFinal: 'Proyección Final',
    variance: 'Varianza',
    description: 'Descripción',
    actual: 'Real',
    committed: 'Comprometido',
    forecast: 'Pronóstico',
    total: 'Total',
    cashPosition: 'Posición de Caja',
    budgetRemaining: 'Presupuesto Restante',
    burnRate: 'Tasa de Consumo',
    projectedCompletionDate: 'Fecha Proyectada',
    exportSage: 'Exportar a Sage 300 CRE',
    exportCsv: 'Exportar CSV',
    print: 'Imprimir',
    thermalWarning: 'Térmica y Humedad 2% sobre presupuesto. Revisar compras recientes.',
    // Cards
    cards: 'Tarjetas',
    cardHolder: 'Titular',
    cardType: 'Tipo de Tarjeta',
    projectsCol: 'Proyecto(s)',
    categoryLimitCol: 'Límite de Categoría',
    perTxnLimit: 'Límite por Txn',
    dailyLimitCol: 'Límite Diario',
    statusLabel: 'Estado',
    employeeLabel: 'Empleado',
    assignToProjects: 'Asignar a Proyecto(s)',
    categoryRestrictions: 'Restricciones de Categoría',
    perTransactionLimit: 'Límite por Transacción',
    dailyLimit: 'Límite Diario',
    approvalRequiredAbove: 'Aprobación requerida sobre',
    autoCodeToProject: 'Codificar automáticamente al proyecto',
    autoCodeHelp: 'Las transacciones se codificarán automáticamente al proyecto asignado',
    physical: 'Física',
    virtual: 'Virtual',
    holdCmdMultiple: 'Mantener Cmd para selección múltiple',
    // Header
    demoMode: 'Modo Demo — Ramp para Construcción',
    switchRole: 'Cambiar rol',
    languageLabel: 'Idioma',
    // Dashboard drilldowns
    projectsByStatus: 'Proyectos por estado',
    spendBreakdown: 'Desglose de gastos este mes',
    cardTransactions: 'Transacciones con tarjeta',
    billPayVendors: 'Pago a proveedores',
    reimbursements: 'Reembolsos',
    vsLastMonth: 'vs. mes anterior ($298K)',
    addedThisQuarter: '4 proyectos agregados este trimestre · 0 completados',
    // Command palette
    searchPages: 'Buscar páginas...',
    noResults: 'Sin resultados',
  },
  pt: {
    projects: 'Projetos',
    activeProjects: 'Projetos Ativos',
    monthlySpend: 'Gasto Mensal',
    receiptRate: 'Taxa de Recibos',
    overBudget: 'Acima do Orçamento',
    submitReceipt: 'Enviar recibo',
    viewProject: 'Ver projeto',
    newProject: 'Novo projeto',
    onTrack: 'No Prazo',
    underBudget: 'Abaixo do Orçamento',
    replayDemo: 'Repetir Demo',
    smsReceiptFlow: 'Fluxo de Recibos por SMS',
    smsSubtitle: 'Trabalhadores de campo codificam transações e enviam recibos por mensagem de texto',
    realTimeCoding: 'Codificação de Transações em Tempo Real',
    waitingSms: 'Aguardando conclusão do fluxo SMS...',
    howItWorks: 'Como funciona',
    howItWorksBody: 'Ramp envia um SMS quando um cartão é usado. O trabalhador de campo responde com um número de projeto e palavra-chave do código de custo. A IA associa ao código CSI correto, captura a foto do recibo e aprova automaticamente se abaixo do limite estabelecido. Nenhum download de aplicativo necessário.',
    receiptCaptured: 'Recibo Capturado',
    aiCostCoded: 'Codificado por IA',
    autoApproved: 'Auto-Aprovado',
    underThreshold: 'Abaixo do limite de $500',
    issueNewCard: 'Emitir novo cartão',
    issueCard: 'Emitir Cartão',
    preferredLanguage: 'Idioma Preferido',
    preferredLanguageHelp: 'Notificações SMS e recibos serão enviados neste idioma',
    languageBanner: 'Idioma preferido do Oscar: Português — Notificações SMS e recibos enviados em português',
    cancel: 'Cancelar',
    createProject: 'Criar Projeto',
    budget: 'orçamento',
    spent: 'gasto',
    ofBudgetUsed: 'do orçamento utilizado',
    completion: 'Conclusão',
  },
  zh: {
    projects: '项目',
    activeProjects: '活跃项目',
    monthlySpend: '月度支出',
    receiptRate: '收据率',
    overBudget: '超出预算',
    submitReceipt: '提交收据',
    viewProject: '查看项目',
    newProject: '新项目',
    onTrack: '进展正常',
    underBudget: '低于预算',
    replayDemo: '重播演示',
    smsReceiptFlow: '短信收据流程',
    smsSubtitle: '现场工人通过短信编码交易并提交收据',
    realTimeCoding: '实时交易编码',
    waitingSms: '等待短信流程完成...',
    howItWorks: '如何运作',
    howItWorksBody: 'Ramp在刷卡时发送短信。现场工人回复项目编号和成本代码关键词。AI将其匹配到正确的CSI代码，捕获收据照片，如果低于设定阈值则自动批准。无需下载应用程序。',
    receiptCaptured: '收据已捕获',
    aiCostCoded: 'AI成本编码',
    autoApproved: '自动批准',
    underThreshold: '低于$500阈值',
    issueNewCard: '发行新卡',
    issueCard: '发行卡片',
    preferredLanguage: '首选语言',
    preferredLanguageHelp: '短信通知和收据提示将以此语言发送',
    languageBanner: 'Oscar的首选语言：中文 — 短信通知和收据以中文发送',
    cancel: '取消',
    createProject: '创建项目',
    budget: '预算',
    spent: '已花费',
    ofBudgetUsed: '预算已使用',
    completion: '完成度',
  },
  pl: {
    projects: 'Projekty',
    activeProjects: 'Aktywne Projekty',
    monthlySpend: 'Miesięczne Wydatki',
    receiptRate: 'Wskaźnik Paragonów',
    overBudget: 'Przekroczony Budżet',
    submitReceipt: 'Wyślij paragon',
    viewProject: 'Zobacz projekt',
    newProject: 'Nowy projekt',
    onTrack: 'Zgodnie z Planem',
    underBudget: 'Poniżej Budżetu',
    replayDemo: 'Powtórz Demo',
    smsReceiptFlow: 'Przepływ Paragonów SMS',
    smsSubtitle: 'Pracownicy terenowi kodują transakcje i przesyłają paragony wiadomością tekstową',
    realTimeCoding: 'Kodowanie Transakcji w Czasie Rzeczywistym',
    waitingSms: 'Oczekiwanie na zakończenie przepływu SMS...',
    howItWorks: 'Jak to działa',
    howItWorksBody: 'Ramp wysyła SMS po użyciu karty. Pracownik terenowy odpowiada numerem projektu i słowem kluczowym kodu kosztów. AI dopasowuje go do prawidłowego kodu CSI, przechwytuje zdjęcie paragonu i automatycznie zatwierdza, jeśli jest poniżej ustalonego progu. Nie wymaga pobierania aplikacji.',
    receiptCaptured: 'Paragon Przechwycony',
    aiCostCoded: 'Zakodowane przez AI',
    autoApproved: 'Auto-Zatwierdzone',
    underThreshold: 'Poniżej progu $500',
    issueNewCard: 'Wydaj nową kartę',
    issueCard: 'Wydaj Kartę',
    preferredLanguage: 'Preferowany Język',
    preferredLanguageHelp: 'Powiadomienia SMS i paragony będą wysyłane w tym języku',
    languageBanner: 'Preferowany język Oscara: Polski — Powiadomienia SMS i paragony wysyłane po polsku',
    cancel: 'Anuluj',
    createProject: 'Utwórz Projekt',
    budget: 'budżet',
    spent: 'wydano',
    ofBudgetUsed: 'budżetu wykorzystano',
    completion: 'Ukończenie',
  },
};

export function translateStatus(status, lang) {
  const statusMap = {
    'On Track': 'onTrack',
    'Over Budget': 'overBudget',
    'Under Budget': 'underBudget',
  };
  const key = statusMap[status];
  if (!key) return status;
  return translations[lang]?.[key] || status;
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
